version: '3.8'

services:
  django:
    build:
      context: .
    image: django-docker:0.0.1
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
